sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
install:
  - mvn -q install -DskipTests=true -B -V
script: mvn clean verify -B -V

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

after_success:
  - bash <(curl -s https://codecov.io/bash)
