sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
install:
  - mvn -q install -DskipTests=true -B -V
script: mvn clean verify -B -V
jdk:
   - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)